name: CI

on:
  schedule:
    - cron: '0 14 * * 2,5'
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Dependencies
        run: npm install
        continue-on-error: true

      - name: Run Cypress Tests with Cypress Cloud        
        run: |
          npx cypress run
        continue-on-error: true
      
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install jq
        run: sudo apt-get install jq
  
      - name: Clean Up Allure Results
        run: |
          for file in allure-results/*.json; do
            jq 'walk(if type == "object" and .excluded then del(.excluded) else . end)' "$file" > temp.json && mv temp.json "$file"
          done
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          curl -o allure-commandline.zip -L "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip"
          unzip -o allure-commandline.zip -d allure
          export PATH=$PATH:$PWD/allure/allure-2.13.9/bin
          allure generate allure-results --clean -o allure-report
          mv -f allure-report/history allure-results/history
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_dir: ./allure-report
        continue-on-error: true